version: '3'
services:
        weither:
                build: .
                ports:
                        - "4000:4000"
                extra_hosts:
                        - "host.docker.internal:172.17.0.1"

